### ISSUE TITLE
[Android] 增加远程图片

### ISSUE THREAD

**Issue by 0xLevin** [rnkit/rnkit-excard#1]
增加 android 端的远程图片识别

**Comment by rainerpiao** [comment]
Add Module ExBankCardSDK And ExCardSDK In Your Main Project。
这两个module没有上传，编译报错了，能分享出来吗？是需要收费的吗？

**Comment by 0xLevin** [comment]
@rainerpiao 收费的，绑定包名，无法分享哈。

**Comment by dajinbao111** [comment]
收费就说清楚，引进来编译不了，浪费时间
