### ISSUE TITLE
Example 项目运行时报错

### ISSUE THREAD

**Issue by hanpanpan200** [rnkit/rnkit-excard#3]
本地环境：

>node: v6.10.3
> react-native@0.44.0

首先通过以下命令来运行了 Example 项目：
```
npm i
react-native run-ios
```

随后报错：

> Unable to resolve module 'rnkit-excard' from `/Example/app.js`
> Module doesn't exist in the module map or in these directories: `node_modules`

然后发现 Example项目的 `package.json`中的 `dependencies`中并没有 'rnkit-excard'

手动安装：

```
npm i rnkit-excard -S
```
再次运行，下面的代码仍然报错：

```
import RNKitExcard from 'rnkit-excard';

RNKitExcard.config({
  DisplayLogo: false
})

```
错误信息中指出，`RNKitExcard` 的值是 `undefined`

请问你是怎样 run 这个 Example 项目的？

**Comment by 0xLevin** [comment]
有没有手动导入 sdk？

**Comment by hanpanpan200** [comment]
Hi @simman 

多谢回复。你说的这个sdk 指的是？

我执行的是 
```
react-native link
```

打开iOS项目也检查了一下配置，的确导入了 `rnkit-excard` 的原生工程。这个 readme 写完之后，你自己有照着操作一遍么？操作的时候是否自己还有别的配置没有写到 readme 里面？

**Comment by 0xLevin** [comment]
sdk 是易道博识-图像识别提供的, 因为它们的sdk是绑定包名, 并不是通用的, 所以在模块里面没有提供。

另外 Example 工程的确存在问题。你可以重新 init 一个工程进行测试。

我们生产环境已经有两个产品在用这个库了，没有问题。

**Comment by hanpanpan200** [comment]
Hi @simman 

明白了,易道博识-图像识 是一个提供图像识别服务厂商是么？

你的这个包是为那个收费的SDK定制的 react-native 插件是么？

不过还是提一点建议，可以在  Readme 里面稍微描述一下，这个包是基于`易道博识-图像识别SDK`定制的。
